// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const navBarStyles = {
  root: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-9)',
    height: 'var(--nav-h)',
    padding: '0 var(--space-8)',
    background: 'var(--surface-panel)',
    borderBottom: 'var(--border-width) solid var(--border-hairline)'
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-5)',
    flex: 'none'
  },
  list: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-8)',
    marginLeft: 'auto',
    listStyle: 'none',
    margin: '0 0 0 auto',
    padding: 0
  },
  item: {
    fontFamily: 'var(--font-display)',
    fontSize: 'var(--text-xs)',
    letterSpacing: 'var(--tracking-wide)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    background: 'none',
    border: 0,
    padding: 'var(--space-3) 0',
    position: 'relative',
    transition: 'color var(--transition-base)'
  },
  rule: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -1,
    height: 'var(--border-width-thick)',
    background: 'var(--ink-white)'
  },
  tail: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-5)',
    flex: 'none'
  }
};
function NavBar({
  brand,
  items = [],
  active,
  onSelect,
  tail,
  style,
  ...rest
}) {
  const [hover, setHover] = React.useState(null);
  return /*#__PURE__*/React.createElement("nav", _extends({}, rest, {
    style: {
      ...navBarStyles.root,
      ...style
    }
  }), brand && /*#__PURE__*/React.createElement("div", {
    style: navBarStyles.brand
  }, brand), /*#__PURE__*/React.createElement("ul", {
    style: navBarStyles.list
  }, items.map(it => {
    const item = typeof it === 'string' ? {
      id: it,
      label: it
    } : it;
    const isActive = active === item.id;
    return /*#__PURE__*/React.createElement("li", {
      key: item.id
    }, /*#__PURE__*/React.createElement("button", {
      type: "button",
      onClick: () => onSelect?.(item.id),
      onMouseEnter: () => setHover(item.id),
      onMouseLeave: () => setHover(null),
      "aria-current": isActive ? 'page' : undefined,
      style: {
        ...navBarStyles.item,
        color: isActive || hover === item.id ? 'var(--text-primary)' : 'var(--text-muted)'
      }
    }, item.label, isActive && /*#__PURE__*/React.createElement("span", {
      "aria-hidden": "true",
      style: navBarStyles.rule
    })));
  })), tail && /*#__PURE__*/React.createElement("div", {
    style: navBarStyles.tail
  }, tail));
}

export { NavBar };
