// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const tabsStyles = {
  root: {
    display: 'flex',
    alignItems: 'stretch',
    borderBottom: 'var(--border-width) solid var(--border-hairline)'
  },
  tab: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--space-4)',
    padding: 'var(--space-5) var(--space-7)',
    background: 'none',
    border: 0,
    cursor: 'pointer',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-xs)',
    fontWeight: 'var(--weight-medium)',
    letterSpacing: 'var(--tracking-wider)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    transition: 'color var(--transition-base),background-color var(--transition-base)'
  },
  rule: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -1,
    height: 'var(--border-width-thick)',
    background: 'var(--ink-white)'
  },
  segRoot: {
    display: 'inline-flex',
    border: 'var(--border-width) solid var(--border-default)'
  },
  segTab: {
    padding: 'var(--space-4) var(--space-6)',
    background: 'none',
    border: 0,
    borderRight: 'var(--border-width) solid var(--border-default)',
    cursor: 'pointer',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-xs)',
    letterSpacing: 'var(--tracking-wider)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    transition: 'color var(--transition-base),background-color var(--transition-base)'
  }
};
function Tabs({
  items = [],
  active,
  onSelect,
  variant = 'underline',
  style,
  ...rest
}) {
  const [hover, setHover] = React.useState(null);
  const list = items.map(it => typeof it === 'string' ? {
    id: it,
    label: it
  } : it);
  if (variant === 'segmented') {
    return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
      role: "tablist",
      style: {
        ...tabsStyles.segRoot,
        ...style
      }
    }), list.map((item, i) => {
      const isActive = active === item.id;
      return /*#__PURE__*/React.createElement("button", {
        key: item.id,
        type: "button",
        role: "tab",
        "aria-selected": isActive,
        onClick: () => onSelect?.(item.id),
        onMouseEnter: () => setHover(item.id),
        onMouseLeave: () => setHover(null),
        style: {
          ...tabsStyles.segTab,
          borderRight: i === list.length - 1 ? 0 : 'var(--border-width) solid var(--border-default)',
          color: isActive ? 'var(--text-inverse)' : hover === item.id ? 'var(--text-primary)' : 'var(--text-muted)',
          background: isActive ? 'var(--ink-white)' : hover === item.id ? 'var(--surface-hover)' : 'transparent'
        }
      }, item.icon, item.label);
    }));
  }
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    role: "tablist",
    style: {
      ...tabsStyles.root,
      ...style
    }
  }), list.map(item => {
    const isActive = active === item.id;
    return /*#__PURE__*/React.createElement("button", {
      key: item.id,
      type: "button",
      role: "tab",
      "aria-selected": isActive,
      onClick: () => onSelect?.(item.id),
      onMouseEnter: () => setHover(item.id),
      onMouseLeave: () => setHover(null),
      style: {
        ...tabsStyles.tab,
        color: isActive || hover === item.id ? 'var(--text-primary)' : 'var(--text-muted)',
        background: hover === item.id && !isActive ? 'var(--surface-hover)' : 'transparent'
      }
    }, item.icon, item.label, item.count != null && /*#__PURE__*/React.createElement("span", {
      style: {
        color: 'var(--text-disabled)'
      }
    }, item.count), isActive && /*#__PURE__*/React.createElement("span", {
      "aria-hidden": "true",
      style: tabsStyles.rule
    }));
  }));
}

export { Tabs };
