// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const checkboxStyles = {
  root: {
    display: 'inline-flex',
    alignItems: 'flex-start',
    gap: 'var(--space-5)',
    cursor: 'pointer',
    minWidth: 0
  },
  box: {
    position: 'relative',
    flex: 'none',
    width: 15,
    height: 15,
    marginTop: 1,
    background: 'var(--surface-inset)',
    border: 'var(--border-width) solid var(--border-default)',
    borderRadius: 'var(--radius-none)',
    transition: 'border-color var(--transition-base),background-color var(--transition-base)'
  },
  mark: {
    position: 'absolute',
    inset: 3,
    background: 'var(--ink-white)'
  },
  dash: {
    position: 'absolute',
    left: 2,
    right: 2,
    top: 6,
    height: 2,
    background: 'var(--text-muted)'
  },
  text: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-base)',
    color: 'var(--text-secondary)',
    letterSpacing: 'var(--tracking-normal)'
  },
  desc: {
    display: 'block',
    fontSize: 'var(--text-xs)',
    color: 'var(--text-muted)',
    marginTop: 'var(--space-2)'
  }
};
function Checkbox({
  checked,
  indeterminate = false,
  disabled = false,
  label,
  description,
  onChange,
  style,
  ...rest
}) {
  const [hover, setHover] = React.useState(false);
  return /*#__PURE__*/React.createElement("label", {
    style: {
      ...checkboxStyles.root,
      ...(disabled ? {
        cursor: 'not-allowed',
        opacity: .5
      } : null),
      ...style
    },
    onMouseEnter: () => setHover(true),
    onMouseLeave: () => setHover(false)
  }, /*#__PURE__*/React.createElement("input", _extends({}, rest, {
    type: "checkbox",
    checked: !!checked,
    disabled: disabled,
    onChange: onChange,
    style: {
      position: 'absolute',
      opacity: 0,
      width: 0,
      height: 0
    }
  })), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...checkboxStyles.box,
      ...(hover && !disabled ? {
        borderColor: 'var(--border-strong)'
      } : null),
      ...(checked && !indeterminate ? {
        borderColor: 'var(--border-loud)'
      } : null)
    }
  }, checked && !indeterminate && /*#__PURE__*/React.createElement("span", {
    style: checkboxStyles.mark
  }), indeterminate && /*#__PURE__*/React.createElement("span", {
    style: checkboxStyles.dash
  })), label && /*#__PURE__*/React.createElement("span", {
    style: checkboxStyles.text
  }, label, description && /*#__PURE__*/React.createElement("span", {
    style: checkboxStyles.desc
  }, description)));
}

export { Checkbox };
