// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const fieldStyles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-3)',
    minWidth: 0
  },
  label: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-xs)',
    fontWeight: 'var(--weight-medium)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)'
  },
  row: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 'var(--space-5)'
  },
  hint: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-2xs)',
    letterSpacing: 'var(--tracking-wide)',
    color: 'var(--text-disabled)'
  },
  error: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-2xs)',
    letterSpacing: 'var(--tracking-wide)',
    color: 'var(--accent-blood-red)',
    textTransform: 'uppercase'
  }
};

/** Label / hint / error scaffold shared by every CabalMesh form control. */
function Field({
  label,
  hint,
  error,
  htmlFor,
  required,
  children,
  style,
  ...rest
}) {
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      ...fieldStyles.root,
      ...style
    }
  }), (label || hint) && /*#__PURE__*/React.createElement("div", {
    style: fieldStyles.row
  }, label && /*#__PURE__*/React.createElement("label", {
    htmlFor: htmlFor,
    style: fieldStyles.label
  }, label, required && /*#__PURE__*/React.createElement("span", {
    style: {
      color: 'var(--accent-blood-red)'
    }
  }, " *")), hint && !error && /*#__PURE__*/React.createElement("span", {
    style: fieldStyles.hint
  }, hint)), children, error && /*#__PURE__*/React.createElement("span", {
    style: fieldStyles.error
  }, error));
}

export { Field };
