// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const inputBase = {
  width: '100%',
  minWidth: 0,
  background: 'var(--surface-inset)',
  color: 'var(--text-primary)',
  fontFamily: 'var(--font-mono)',
  fontSize: 'var(--text-base)',
  letterSpacing: 'var(--tracking-normal)',
  borderRadius: 'var(--radius-none)',
  borderWidth: 'var(--border-width)',
  borderStyle: 'solid',
  borderColor: 'var(--border-default)',
  padding: 'var(--field-pad-y) var(--field-pad-x)',
  transition: 'border-color var(--transition-base),box-shadow var(--transition-base)',
  outline: 'none'
};
function Input({
  invalid = false,
  disabled = false,
  prefix,
  suffix,
  multiline = false,
  rows = 4,
  style,
  ...rest
}) {
  const [focus, setFocus] = React.useState(false);
  const shell = {
    ...inputBase,
    ...(invalid ? {
      borderColor: 'var(--accent-blood-red)'
    } : null),
    ...(focus ? {
      borderColor: 'var(--border-focus)',
      boxShadow: 'var(--glow-blue)'
    } : null),
    ...(disabled ? {
      color: 'var(--text-disabled)',
      borderColor: 'var(--border-hairline)',
      cursor: 'not-allowed'
    } : null)
  };
  const Tag = multiline ? 'textarea' : 'input';
  const control = /*#__PURE__*/React.createElement(Tag, _extends({}, rest, {
    rows: multiline ? rows : undefined,
    disabled: disabled,
    "aria-invalid": invalid || undefined,
    onFocus: e => {
      setFocus(true);
      rest.onFocus?.(e);
    },
    onBlur: e => {
      setFocus(false);
      rest.onBlur?.(e);
    },
    style: prefix || suffix ? {
      flex: 1,
      minWidth: 0,
      background: 'transparent',
      border: 0,
      outline: 'none',
      color: 'inherit',
      font: 'inherit',
      letterSpacing: 'inherit',
      padding: 0,
      resize: multiline ? 'vertical' : undefined
    } : {
      ...shell,
      resize: multiline ? 'vertical' : undefined,
      ...style
    }
  }));
  if (!prefix && !suffix) return control;
  return /*#__PURE__*/React.createElement("span", {
    style: {
      ...shell,
      display: 'flex',
      alignItems: 'center',
      gap: 'var(--space-4)',
      ...style
    }
  }, prefix && /*#__PURE__*/React.createElement("span", {
    style: {
      flex: 'none',
      color: 'var(--text-muted)',
      display: 'inline-flex',
      alignItems: 'center'
    }
  }, prefix), control, suffix && /*#__PURE__*/React.createElement("span", {
    style: {
      flex: 'none',
      color: 'var(--text-muted)',
      display: 'inline-flex',
      alignItems: 'center',
      fontSize: 'var(--text-xs)',
      letterSpacing: 'var(--tracking-wide)'
    }
  }, suffix));
}

export { Input };
