// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const radioStyles = {
  root: {
    display: 'inline-flex',
    alignItems: 'flex-start',
    gap: 'var(--space-5)',
    cursor: 'pointer'
  },
  box: {
    position: 'relative',
    flex: 'none',
    width: 15,
    height: 15,
    marginTop: 1,
    background: 'var(--surface-inset)',
    border: 'var(--border-width) solid var(--border-default)',
    transition: 'border-color var(--transition-base)'
  },
  diamond: {
    position: 'absolute',
    inset: 3,
    background: 'var(--ink-white)',
    transform: 'rotate(45deg)'
  },
  text: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-base)',
    color: 'var(--text-secondary)'
  },
  desc: {
    display: 'block',
    fontSize: 'var(--text-xs)',
    color: 'var(--text-muted)',
    marginTop: 'var(--space-2)'
  },
  group: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-5)'
  }
};
function Radio({
  checked,
  disabled = false,
  label,
  description,
  style,
  ...rest
}) {
  const [hover, setHover] = React.useState(false);
  return /*#__PURE__*/React.createElement("label", {
    style: {
      ...radioStyles.root,
      ...(disabled ? {
        cursor: 'not-allowed',
        opacity: .5
      } : null),
      ...style
    },
    onMouseEnter: () => setHover(true),
    onMouseLeave: () => setHover(false)
  }, /*#__PURE__*/React.createElement("input", _extends({}, rest, {
    type: "radio",
    checked: !!checked,
    disabled: disabled,
    style: {
      position: 'absolute',
      opacity: 0,
      width: 0,
      height: 0
    }
  })), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...radioStyles.box,
      ...(hover && !disabled ? {
        borderColor: 'var(--border-strong)'
      } : null),
      ...(checked ? {
        borderColor: 'var(--border-loud)'
      } : null)
    }
  }, checked && /*#__PURE__*/React.createElement("span", {
    style: radioStyles.diamond
  })), label && /*#__PURE__*/React.createElement("span", {
    style: radioStyles.text
  }, label, description && /*#__PURE__*/React.createElement("span", {
    style: radioStyles.desc
  }, description)));
}
function RadioGroup({
  name,
  value,
  options = [],
  onChange,
  style,
  ...rest
}) {
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    role: "radiogroup",
    style: {
      ...radioStyles.group,
      ...style
    }
  }), options.map(o => {
    const opt = typeof o === 'string' ? {
      value: o,
      label: o
    } : o;
    return /*#__PURE__*/React.createElement(Radio, {
      key: opt.value,
      name: name,
      value: opt.value,
      label: opt.label,
      description: opt.description,
      checked: value === opt.value,
      onChange: () => onChange?.(opt.value)
    });
  }));
}

export { Radio, RadioGroup };
