// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const selectBase = {
  width: '100%',
  appearance: 'none',
  WebkitAppearance: 'none',
  background: 'var(--surface-inset)',
  color: 'var(--text-primary)',
  fontFamily: 'var(--font-mono)',
  fontSize: 'var(--text-base)',
  letterSpacing: 'var(--tracking-normal)',
  borderRadius: 'var(--radius-none)',
  borderWidth: 'var(--border-width)',
  borderStyle: 'solid',
  borderColor: 'var(--border-default)',
  padding: 'var(--field-pad-y) var(--space-10) var(--field-pad-y) var(--field-pad-x)',
  transition: 'border-color var(--transition-base),box-shadow var(--transition-base)',
  outline: 'none',
  cursor: 'pointer'
};
function Select({
  options = [],
  invalid = false,
  disabled = false,
  placeholder,
  style,
  children,
  ...rest
}) {
  const [focus, setFocus] = React.useState(false);
  return /*#__PURE__*/React.createElement("span", {
    style: {
      position: 'relative',
      display: 'block',
      minWidth: 0
    }
  }, /*#__PURE__*/React.createElement("select", _extends({}, rest, {
    disabled: disabled,
    "aria-invalid": invalid || undefined,
    onFocus: e => {
      setFocus(true);
      rest.onFocus?.(e);
    },
    onBlur: e => {
      setFocus(false);
      rest.onBlur?.(e);
    },
    style: {
      ...selectBase,
      ...(invalid ? {
        borderColor: 'var(--accent-blood-red)'
      } : null),
      ...(focus ? {
        borderColor: 'var(--border-focus)',
        boxShadow: 'var(--glow-blue)'
      } : null),
      ...(disabled ? {
        color: 'var(--text-disabled)',
        borderColor: 'var(--border-hairline)',
        cursor: 'not-allowed'
      } : null),
      ...style
    }
  }), placeholder && /*#__PURE__*/React.createElement("option", {
    value: ""
  }, placeholder), options.map(o => {
    const opt = typeof o === 'string' ? {
      value: o,
      label: o
    } : o;
    return /*#__PURE__*/React.createElement("option", {
      key: opt.value,
      value: opt.value
    }, opt.label);
  }), children), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      position: 'absolute',
      right: 'var(--space-5)',
      top: '50%',
      width: 6,
      height: 6,
      marginTop: -6,
      borderRight: 'var(--border-width) solid var(--border-strong)',
      borderBottom: 'var(--border-width) solid var(--border-strong)',
      transform: 'rotate(45deg)',
      pointerEvents: 'none'
    }
  }));
}

export { Select };
