// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const switchStyles = {
  root: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--space-5)',
    cursor: 'pointer'
  },
  track: {
    position: 'relative',
    flex: 'none',
    width: 34,
    height: 16,
    background: 'var(--surface-inset)',
    border: 'var(--border-width) solid var(--border-default)',
    transition: 'border-color var(--transition-base),background-color var(--transition-base)'
  },
  knob: {
    position: 'absolute',
    top: 1,
    left: 1,
    width: 14,
    height: 12,
    background: 'var(--text-muted)',
    transition: 'transform var(--dur-fast) var(--ease-step-coarse),background-color var(--transition-base)'
  },
  text: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-base)',
    color: 'var(--text-secondary)'
  },
  state: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-2xs)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    minWidth: '3ch'
  }
};
function Switch({
  checked = false,
  disabled = false,
  label,
  showState = false,
  onChange,
  style,
  ...rest
}) {
  return /*#__PURE__*/React.createElement("label", {
    style: {
      ...switchStyles.root,
      ...(disabled ? {
        cursor: 'not-allowed',
        opacity: .5
      } : null),
      ...style
    }
  }, /*#__PURE__*/React.createElement("input", _extends({}, rest, {
    type: "checkbox",
    role: "switch",
    checked: checked,
    disabled: disabled,
    onChange: onChange,
    style: {
      position: 'absolute',
      opacity: 0,
      width: 0,
      height: 0
    }
  })), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...switchStyles.track,
      ...(checked ? {
        borderColor: 'var(--border-loud)'
      } : null)
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      ...switchStyles.knob,
      transform: checked ? 'translateX(17px)' : 'translateX(0)',
      background: checked ? 'var(--ink-white)' : 'var(--text-muted)'
    }
  })), label && /*#__PURE__*/React.createElement("span", {
    style: switchStyles.text
  }, label), showState && /*#__PURE__*/React.createElement("span", {
    style: {
      ...switchStyles.state,
      color: checked ? 'var(--accent-acid-green)' : 'var(--text-muted)'
    }
  }, checked ? 'ON' : 'OFF'));
}

export { Switch };
