// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const badgeTones = {
  neutral: {
    color: 'var(--text-secondary)',
    borderColor: 'var(--border-default)'
  },
  quiet: {
    color: 'var(--text-muted)',
    borderColor: 'var(--border-hairline)'
  },
  loud: {
    color: 'var(--text-inverse)',
    borderColor: 'var(--ink-white)',
    background: 'var(--ink-white)'
  },
  info: {
    color: 'var(--accent-neon-blue)',
    borderColor: 'color-mix(in srgb,var(--accent-neon-blue) 55%,transparent)'
  },
  success: {
    color: 'var(--accent-acid-green)',
    borderColor: 'color-mix(in srgb,var(--accent-acid-green) 55%,transparent)'
  },
  alert: {
    color: 'var(--accent-blood-red)',
    borderColor: 'color-mix(in srgb,var(--accent-blood-red) 55%,transparent)'
  }
};
const badgeBase = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: 'var(--space-3)',
  fontFamily: 'var(--font-mono)',
  fontWeight: 'var(--weight-medium)',
  textTransform: 'uppercase',
  letterSpacing: 'var(--tracking-wider)',
  lineHeight: 'var(--leading-none)',
  borderRadius: 'var(--radius-none)',
  borderWidth: 'var(--border-width)',
  borderStyle: 'solid',
  background: 'transparent',
  whiteSpace: 'nowrap'
};
function Badge({
  tone = 'neutral',
  size = 'md',
  icon,
  style,
  children,
  ...rest
}) {
  const dims = size === 'sm' ? {
    fontSize: 'var(--text-2xs)',
    padding: '2px var(--space-3)'
  } : {
    fontSize: 'var(--text-xs)',
    padding: 'var(--space-2) var(--space-4)'
  };
  return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    style: {
      ...badgeBase,
      ...dims,
      ...badgeTones[tone],
      ...style
    }
  }), icon, children);
}

export { Badge };
