// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const buttonSizes = {
  sm: {
    padding: 'var(--btn-pad-y-sm) var(--btn-pad-x-sm)',
    fontSize: 'var(--text-xs)',
    letterSpacing: 'var(--tracking-wide)'
  },
  md: {
    padding: 'var(--btn-pad-y) var(--btn-pad-x)',
    fontSize: 'var(--text-sm)',
    letterSpacing: 'var(--tracking-wide)'
  },
  lg: {
    padding: 'var(--space-6) var(--space-9)',
    fontSize: 'var(--text-base)',
    letterSpacing: 'var(--tracking-wider)'
  }
};
const buttonTones = {
  primary: {
    idle: {
      color: 'var(--text-primary)',
      borderColor: 'var(--border-loud)',
      background: 'transparent'
    },
    hover: {
      color: 'var(--text-inverse)',
      background: 'var(--ink-white)',
      borderColor: 'var(--ink-white)'
    }
  },
  secondary: {
    idle: {
      color: 'var(--text-secondary)',
      borderColor: 'var(--border-default)',
      background: 'transparent'
    },
    hover: {
      color: 'var(--text-primary)',
      borderColor: 'var(--border-strong)',
      background: 'var(--surface-hover)'
    }
  },
  ghost: {
    idle: {
      color: 'var(--text-muted)',
      borderColor: 'transparent',
      background: 'transparent'
    },
    hover: {
      color: 'var(--text-primary)',
      borderColor: 'transparent',
      background: 'var(--surface-hover)'
    }
  },
  danger: {
    idle: {
      color: 'var(--accent-blood-red)',
      borderColor: 'var(--accent-blood-red)',
      background: 'transparent'
    },
    hover: {
      color: 'var(--text-inverse)',
      background: 'var(--accent-blood-red)',
      borderColor: 'var(--accent-blood-red)'
    }
  },
  signal: {
    idle: {
      color: 'var(--accent-neon-blue)',
      borderColor: 'var(--accent-neon-blue)',
      background: 'transparent'
    },
    hover: {
      color: 'var(--text-inverse)',
      background: 'var(--accent-neon-blue)',
      borderColor: 'var(--accent-neon-blue)'
    }
  }
};
const buttonBase = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 'var(--space-4)',
  fontFamily: 'var(--font-display)',
  textTransform: 'uppercase',
  fontWeight: 'var(--weight-regular)',
  lineHeight: 'var(--leading-none)',
  borderRadius: 'var(--radius-none)',
  borderWidth: 'var(--border-width)',
  borderStyle: 'solid',
  cursor: 'pointer',
  textDecoration: 'none',
  whiteSpace: 'nowrap',
  transition: 'color var(--transition-base),background-color var(--transition-base),border-color var(--transition-base),opacity var(--transition-base)'
};
function Button({
  tone = 'secondary',
  size = 'md',
  block = false,
  disabled = false,
  as = 'button',
  icon,
  iconAfter,
  style,
  children,
  ...rest
}) {
  const [hover, setHover] = React.useState(false);
  const [press, setPress] = React.useState(false);
  const t = buttonTones[tone] || buttonTones.secondary;
  const Tag = as;
  return /*#__PURE__*/React.createElement(Tag, _extends({}, rest, {
    disabled: Tag === 'button' ? disabled : undefined,
    "aria-disabled": disabled || undefined,
    onMouseEnter: () => setHover(true),
    onMouseLeave: () => {
      setHover(false);
      setPress(false);
    },
    onMouseDown: () => setPress(true),
    onMouseUp: () => setPress(false),
    style: {
      ...buttonBase,
      ...buttonSizes[size],
      ...t.idle,
      ...(hover && !disabled ? t.hover : null),
      ...(press && !disabled ? {
        opacity: 0.72
      } : null),
      ...(block ? {
        display: 'flex',
        width: '100%'
      } : null),
      ...(disabled ? {
        color: 'var(--text-disabled)',
        borderColor: 'var(--border-hairline)',
        background: 'transparent',
        cursor: 'not-allowed'
      } : null),
      ...style
    }
  }), icon, children, iconAfter);
}

export { Button };
