// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const dividerOrnamentStyles = {
  wrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-5)',
    width: '100%'
  },
  rule: {
    flex: 1,
    height: 'var(--border-width)',
    background: 'var(--border-hairline)'
  },
  diamond: {
    width: 7,
    height: 7,
    flex: 'none',
    border: 'var(--border-width) solid var(--border-strong)',
    transform: 'rotate(45deg)'
  },
  label: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-2xs)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    whiteSpace: 'nowrap'
  }
};
function Divider({
  ornament = false,
  label,
  vertical = false,
  tone = 'hairline',
  style,
  ...rest
}) {
  const color = tone === 'strong' ? 'var(--border-strong)' : tone === 'default' ? 'var(--border-default)' : 'var(--border-hairline)';
  if (vertical) return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    "aria-hidden": "true",
    style: {
      width: 'var(--border-width)',
      alignSelf: 'stretch',
      background: color,
      flex: 'none',
      ...style
    }
  }));
  if (!ornament && !label) return /*#__PURE__*/React.createElement("hr", _extends({}, rest, {
    style: {
      border: 0,
      borderTop: `var(--border-width) solid ${color}`,
      margin: 0,
      ...style
    }
  }));
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      ...dividerOrnamentStyles.wrap,
      ...style
    }
  }), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...dividerOrnamentStyles.rule,
      background: color
    }
  }), label && /*#__PURE__*/React.createElement("span", {
    style: dividerOrnamentStyles.label
  }, label), ornament && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: dividerOrnamentStyles.diamond
  }), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...dividerOrnamentStyles.rule,
      background: color
    }
  }));
}

export { Divider };
