// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const iconButtonSizes = {
  sm: 26,
  md: 32,
  lg: 40
};
const iconButtonGlyph = {
  sm: 12,
  md: 16,
  lg: 20
};
const iconButtonBase = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  flex: 'none',
  background: 'transparent',
  borderRadius: 'var(--radius-none)',
  borderWidth: 'var(--border-width)',
  borderStyle: 'solid',
  cursor: 'pointer',
  padding: 0,
  color: 'var(--text-muted)',
  transition: 'color var(--transition-base),border-color var(--transition-base),background-color var(--transition-base)'
};
function IconButton({
  size = 'md',
  tone = 'outline',
  active = false,
  disabled = false,
  label,
  children,
  style,
  ...rest
}) {
  const [hover, setHover] = React.useState(false);
  const px = iconButtonSizes[size] || iconButtonSizes.md;
  return /*#__PURE__*/React.createElement("button", _extends({}, rest, {
    type: rest.type || 'button',
    "aria-label": label,
    "aria-pressed": active || undefined,
    disabled: disabled,
    onMouseEnter: () => setHover(true),
    onMouseLeave: () => setHover(false),
    style: {
      ...iconButtonBase,
      width: px,
      height: px,
      borderColor: tone === 'bare' ? 'transparent' : 'var(--border-default)',
      ...(active ? {
        color: 'var(--text-primary)',
        borderColor: 'var(--border-strong)',
        background: 'var(--surface-active)'
      } : null),
      ...(hover && !disabled ? {
        color: 'var(--text-primary)',
        borderColor: tone === 'bare' ? 'transparent' : 'var(--border-strong)',
        background: 'var(--surface-hover)'
      } : null),
      ...(disabled ? {
        color: 'var(--text-disabled)',
        borderColor: 'var(--border-hairline)',
        cursor: 'not-allowed'
      } : null),
      fontSize: iconButtonGlyph[size],
      ...style
    }
  }), children);
}

export { IconButton };
