// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
/** The 14 protocol glyphs from the brand book's ICON SYSTEM plate. */
const MESH_ICONS = ['node', 'agent', 'intent', 'mesh', 'proof', 'escrow', 'vault', 'reputation', 'signal', 'encrypt', 'identity', 'bridge', 'relayer', 'log'];
const iconBase = {
  display: 'inline-block',
  flex: 'none',
  imageRendering: 'pixelated',
  verticalAlign: 'middle',
  userSelect: 'none'
};
function Icon({
  name,
  src,
  size = 20,
  tint,
  opacity,
  basePath = 'assets/icons',
  alt,
  style,
  ...rest
}) {
  const url = src || `${basePath}/${name}.png`;
  if (tint) {
    return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
      role: "img",
      "aria-label": alt ?? name,
      style: {
        ...iconBase,
        width: size,
        height: size,
        opacity,
        background: tint,
        WebkitMaskImage: `url("${url}")`,
        maskImage: `url("${url}")`,
        WebkitMaskSize: 'contain',
        maskSize: 'contain',
        WebkitMaskRepeat: 'no-repeat',
        maskRepeat: 'no-repeat',
        WebkitMaskPosition: 'center',
        maskPosition: 'center',
        ...style
      }
    }));
  }
  return /*#__PURE__*/React.createElement("img", _extends({}, rest, {
    src: url,
    alt: alt ?? name,
    style: {
      ...iconBase,
      width: size,
      height: size,
      opacity,
      ...style
    }
  }));
}

export { Icon, MESH_ICONS };
