// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const logoVariants = {
  primary: 'primary-logo.png',
  wordmark: 'wordmark-stacked.png',
  symbol: 'symbol-mark.png',
  icon: 'icon-mark.png',
  minimal: 'minimal-mark.png',
  hero: 'hero-lockup.png',
  emblem: 'oracle-emblem.png'
};
const logoTypeStyles = {
  root: {
    display: 'inline-flex',
    alignItems: 'center'
  },
  line: {
    fontFamily: 'var(--type-wordmark-family)',
    textTransform: 'uppercase',
    letterSpacing: 'var(--type-wordmark-tracking)',
    lineHeight: 'var(--leading-tight)',
    textIndent: 'var(--type-wordmark-tracking)',
    whiteSpace: 'nowrap'
  }
};
function Logo({
  variant = 'wordmark',
  size = 48,
  tint,
  basePath = 'assets/logo',
  title = 'Cabal Mesh',
  style,
  ...rest
}) {
  const url = `${basePath}/${logoVariants[variant] || logoVariants.wordmark}`;
  if (tint) {
    return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
      role: "img",
      "aria-label": title,
      style: {
        display: 'inline-block',
        flex: 'none',
        height: size,
        width: size,
        background: tint,
        WebkitMaskImage: `url("${url}")`,
        maskImage: `url("${url}")`,
        WebkitMaskSize: 'contain',
        maskSize: 'contain',
        WebkitMaskRepeat: 'no-repeat',
        maskRepeat: 'no-repeat',
        WebkitMaskPosition: 'center',
        maskPosition: 'center',
        ...style
      }
    }));
  }
  return /*#__PURE__*/React.createElement("img", _extends({}, rest, {
    src: url,
    alt: title,
    style: {
      display: 'block',
      flex: 'none',
      height: size,
      width: 'auto',
      imageRendering: 'pixelated',
      ...style
    }
  }));
}

/** Live-type wordmark for tight UI chrome, where the raster mark would blur. */
function LogoType({
  size = 'var(--text-base)',
  stacked = false,
  tone = 'var(--text-primary)',
  style,
  ...rest
}) {
  return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    "aria-label": "Cabal Mesh",
    style: {
      ...logoTypeStyles.root,
      ...(stacked ? {
        flexDirection: 'column',
        alignItems: 'center'
      } : null),
      ...style
    }
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      ...logoTypeStyles.line,
      fontSize: size,
      color: tone
    }
  }, "Cabal"), !stacked && /*#__PURE__*/React.createElement("span", {
    style: {
      ...logoTypeStyles.line,
      fontSize: size,
      color: tone
    }
  }, "Mesh"), stacked && /*#__PURE__*/React.createElement("span", {
    style: {
      ...logoTypeStyles.line,
      fontSize: size,
      color: tone
    }
  }, "Mesh"));
}

export { Logo, LogoType };
