// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const panelTones = {
  panel: {
    background: 'var(--surface-panel)'
  },
  void: {
    background: 'var(--surface-page)'
  },
  raised: {
    background: 'var(--surface-raised)'
  },
  none: {
    background: 'transparent'
  }
};
const panelBorders = {
  hairline: 'var(--border-hairline-style)',
  default: 'var(--border-default-style)',
  strong: 'var(--border-strong-style)',
  loud: 'var(--border-loud-style)',
  none: 'none'
};
const panelStyles = {
  root: {
    position: 'relative',
    borderRadius: 'var(--radius-none)',
    minWidth: 0
  },
  sheen: {
    position: 'absolute',
    inset: 0,
    background: 'var(--panel-sheen)',
    pointerEvents: 'none'
  },
  head: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-5)',
    padding: 'var(--space-4) var(--space-6)'
  },
  label: {
    fontFamily: 'var(--type-label-family)',
    fontSize: 'var(--type-label-size)',
    fontWeight: 'var(--type-label-weight)',
    letterSpacing: 'var(--type-label-tracking)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    whiteSpace: 'nowrap'
  },
  rule: {
    flex: 1,
    height: 'var(--border-width)',
    background: 'var(--border-hairline)'
  },
  body: {
    position: 'relative',
    minWidth: 0
  }
};
const tickCorners = [{
  top: 3,
  left: 3,
  borderTopWidth: 1,
  borderLeftWidth: 1
}, {
  top: 3,
  right: 3,
  borderTopWidth: 1,
  borderRightWidth: 1
}, {
  bottom: 3,
  left: 3,
  borderBottomWidth: 1,
  borderLeftWidth: 1
}, {
  bottom: 3,
  right: 3,
  borderBottomWidth: 1,
  borderRightWidth: 1
}];

/** Corner registration marks. Exported so screens can bracket arbitrary regions. */
function CornerTicks({
  size = 5,
  color = 'var(--border-strong)'
}) {
  return tickCorners.map((c, i) => /*#__PURE__*/React.createElement("span", {
    key: i,
    "aria-hidden": "true",
    style: {
      position: 'absolute',
      width: size,
      height: size,
      borderStyle: 'solid',
      borderWidth: 0,
      borderColor: color,
      pointerEvents: 'none',
      ...c
    }
  }));
}
function Panel({
  label,
  action,
  ticks = true,
  sheen = true,
  pad = true,
  tone = 'panel',
  border = 'hairline',
  style,
  bodyStyle,
  children,
  ...rest
}) {
  const padding = pad === false ? 0 : pad === 'tight' ? 'var(--panel-pad-tight)' : pad === true ? 'var(--panel-pad)' : pad;
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      ...panelStyles.root,
      ...panelTones[tone],
      border: panelBorders[border],
      ...style
    }
  }), sheen && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: panelStyles.sheen
  }), ticks && /*#__PURE__*/React.createElement(CornerTicks, null), (label || action) && /*#__PURE__*/React.createElement("div", {
    style: {
      ...panelStyles.head,
      borderBottom: 'var(--border-hairline-style)'
    }
  }, label && /*#__PURE__*/React.createElement("span", {
    style: panelStyles.label
  }, label), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: panelStyles.rule
  }), action), /*#__PURE__*/React.createElement("div", {
    style: {
      ...panelStyles.body,
      padding,
      ...bodyStyle
    }
  }, children));
}

export { CornerTicks, Panel };
