// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const dotTones = {
  online: {
    color: 'var(--status-online)',
    glow: 'var(--glow-green)'
  },
  alert: {
    color: 'var(--status-alert)',
    glow: 'var(--glow-red)'
  },
  info: {
    color: 'var(--status-info)',
    glow: 'var(--glow-blue)'
  },
  idle: {
    color: 'var(--status-idle)',
    glow: 'none'
  },
  offline: {
    color: 'var(--status-offline)',
    glow: 'none'
  }
};
function StatusDot({
  tone = 'online',
  size = 7,
  pulse = false,
  glow = true,
  label,
  style,
  ...rest
}) {
  const t = dotTones[tone] || dotTones.online;
  const dot = /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      display: 'inline-block',
      flex: 'none',
      width: size,
      height: size,
      background: t.color,
      borderRadius: 'var(--radius-none)',
      boxShadow: glow ? t.glow : 'none',
      animation: pulse ? 'cm-pulse var(--dur-glacial) var(--ease-step) infinite' : 'none'
    }
  });
  if (!label) return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    role: "status",
    "aria-label": tone,
    style: {
      display: 'inline-flex',
      alignItems: 'center',
      ...style
    }
  }), dot);
  return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    role: "status",
    style: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 'var(--space-4)',
      fontFamily: 'var(--font-mono)',
      fontSize: 'var(--text-xs)',
      letterSpacing: 'var(--tracking-wider)',
      textTransform: 'uppercase',
      color: 'var(--text-muted)',
      ...style
    }
  }), dot, label);
}

export { StatusDot };
