// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const dataTableStyles = {
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-sm)'
  },
  th: {
    textAlign: 'left',
    padding: 'var(--space-4) var(--space-6)',
    fontSize: 'var(--text-2xs)',
    fontWeight: 'var(--weight-medium)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    borderBottom: 'var(--border-width) solid var(--border-default)',
    whiteSpace: 'nowrap',
    background: 'var(--surface-panel)'
  },
  td: {
    padding: 'var(--space-5) var(--space-6)',
    color: 'var(--text-secondary)',
    borderBottom: 'var(--border-width) solid var(--border-hairline)',
    letterSpacing: 'var(--tracking-normal)',
    whiteSpace: 'nowrap'
  }
};
function DataTable({
  columns = [],
  rows = [],
  onRowClick,
  selectedIndex,
  empty = 'No records',
  style,
  ...rest
}) {
  const [hover, setHover] = React.useState(-1);
  return /*#__PURE__*/React.createElement("table", _extends({}, rest, {
    style: {
      ...dataTableStyles.table,
      ...style
    }
  }), /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", null, columns.map(c => /*#__PURE__*/React.createElement("th", {
    key: c.key,
    style: {
      ...dataTableStyles.th,
      textAlign: c.align || 'left',
      width: c.width
    }
  }, c.header)))), /*#__PURE__*/React.createElement("tbody", null, rows.length === 0 && /*#__PURE__*/React.createElement("tr", null, /*#__PURE__*/React.createElement("td", {
    colSpan: columns.length,
    style: {
      ...dataTableStyles.td,
      color: 'var(--text-disabled)',
      textAlign: 'center',
      padding: 'var(--space-11)',
      textTransform: 'uppercase',
      letterSpacing: 'var(--tracking-widest)',
      fontSize: 'var(--text-xs)'
    }
  }, empty)), rows.map((r, i) => /*#__PURE__*/React.createElement("tr", {
    key: r.id ?? i,
    onClick: onRowClick ? () => onRowClick(r, i) : undefined,
    onMouseEnter: () => setHover(i),
    onMouseLeave: () => setHover(-1),
    style: {
      cursor: onRowClick ? 'pointer' : 'default',
      background: selectedIndex === i ? 'var(--surface-active)' : hover === i ? 'var(--surface-hover)' : 'transparent',
      transition: 'background-color var(--transition-base)'
    }
  }, columns.map(c => /*#__PURE__*/React.createElement("td", {
    key: c.key,
    style: {
      ...dataTableStyles.td,
      textAlign: c.align || 'left',
      color: c.mono === false ? 'var(--text-secondary)' : undefined,
      ...(c.emphasis ? {
        color: 'var(--text-primary)'
      } : null)
    }
  }, c.render ? c.render(r, i) : r[c.key]))))));
}

export { DataTable };
