// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const meterTones = {
  white: 'var(--ink-white)',
  info: 'var(--accent-neon-blue)',
  success: 'var(--accent-acid-green)',
  alert: 'var(--accent-blood-red)',
  quiet: 'var(--text-muted)'
};
function Meter({
  value = 0,
  max = 100,
  tone = 'white',
  size = 6,
  label,
  readout,
  segments = 0,
  style,
  ...rest
}) {
  const pct = Math.max(0, Math.min(100, value / max * 100));
  const fill = meterTones[tone] || meterTones.white;
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--space-3)',
      minWidth: 0,
      ...style
    }
  }), (label || readout) && /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'flex',
      justifyContent: 'space-between',
      gap: 'var(--space-5)',
      fontFamily: 'var(--font-mono)',
      fontSize: 'var(--text-2xs)',
      letterSpacing: 'var(--tracking-widest)',
      textTransform: 'uppercase'
    }
  }, label && /*#__PURE__*/React.createElement("span", {
    style: {
      color: 'var(--text-muted)'
    }
  }, label), readout && /*#__PURE__*/React.createElement("span", {
    style: {
      color: 'var(--text-secondary)'
    }
  }, readout)), /*#__PURE__*/React.createElement("div", {
    role: "meter",
    "aria-valuenow": value,
    "aria-valuemax": max,
    style: {
      position: 'relative',
      height: size,
      background: 'var(--surface-inset)',
      border: 'var(--border-width) solid var(--border-hairline)'
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      position: 'absolute',
      inset: 0,
      width: `${pct}%`,
      background: fill,
      transition: 'width var(--dur-base) var(--ease-step)'
    }
  }), segments > 0 && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      position: 'absolute',
      inset: 0,
      background: `repeating-linear-gradient(90deg,transparent 0 calc(100%/${segments} - 1px),var(--surface-page) calc(100%/${segments} - 1px) calc(100%/${segments}))`
    }
  })));
}

export { Meter };
