// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const statBlockStyles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-3)',
    minWidth: 0
  },
  label: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-2xs)',
    fontWeight: 'var(--weight-medium)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    whiteSpace: 'nowrap'
  },
  row: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 'var(--space-4)'
  },
  value: {
    fontFamily: 'var(--font-display)',
    color: 'var(--text-primary)',
    letterSpacing: 'var(--tracking-wide)',
    lineHeight: 'var(--leading-none)'
  },
  unit: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-xs)',
    letterSpacing: 'var(--tracking-wide)',
    color: 'var(--text-muted)',
    textTransform: 'uppercase'
  },
  delta: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-xs)',
    letterSpacing: 'var(--tracking-wide)'
  },
  inlineRoot: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--space-4)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-xs)',
    letterSpacing: 'var(--tracking-wider)',
    textTransform: 'uppercase'
  }
};
const statSizes = {
  sm: 'var(--text-lg)',
  md: 'var(--text-xl)',
  lg: 'var(--text-3xl)'
};
function StatBlock({
  label,
  value,
  unit,
  delta,
  deltaTone = 'neutral',
  size = 'md',
  style,
  ...rest
}) {
  const dTone = deltaTone === 'up' ? 'var(--accent-acid-green)' : deltaTone === 'down' ? 'var(--accent-blood-red)' : 'var(--text-muted)';
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      ...statBlockStyles.root,
      ...style
    }
  }), label && /*#__PURE__*/React.createElement("span", {
    style: statBlockStyles.label
  }, label), /*#__PURE__*/React.createElement("span", {
    style: statBlockStyles.row
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      ...statBlockStyles.value,
      fontSize: statSizes[size]
    }
  }, value), unit && /*#__PURE__*/React.createElement("span", {
    style: statBlockStyles.unit
  }, unit), delta && /*#__PURE__*/React.createElement("span", {
    style: {
      ...statBlockStyles.delta,
      color: dTone
    }
  }, delta)));
}

/** The status-bar readout form: "NODES: 1284". */
function StatInline({
  label,
  value,
  tone = 'var(--text-secondary)',
  style,
  ...rest
}) {
  return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    style: {
      ...statBlockStyles.inlineRoot,
      color: 'var(--text-muted)',
      ...style
    }
  }), label, ": ", /*#__PURE__*/React.createElement("span", {
    style: {
      color: tone
    }
  }, value));
}

export { StatBlock, StatInline };
