// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const terminalTones = {
  out: 'var(--text-secondary)',
  dim: 'var(--text-muted)',
  ok: 'var(--accent-acid-green)',
  err: 'var(--accent-blood-red)',
  info: 'var(--accent-neon-blue)',
  loud: 'var(--text-primary)'
};
const terminalStyles = {
  root: {
    position: 'relative',
    background: 'var(--surface-inset)',
    border: 'var(--border-width) solid var(--border-default)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-sm)',
    lineHeight: 'var(--leading-snug)',
    overflow: 'hidden'
  },
  chrome: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-4)',
    padding: 'var(--space-4) var(--space-5)',
    borderBottom: 'var(--border-width) solid var(--border-hairline)'
  },
  pip: {
    width: 5,
    height: 5,
    background: 'var(--text-disabled)'
  },
  title: {
    marginLeft: 'auto',
    fontSize: 'var(--text-2xs)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)'
  },
  body: {
    padding: 'var(--space-5)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-1)',
    overflow: 'auto'
  },
  line: {
    display: 'flex',
    gap: 'var(--space-4)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word'
  },
  caret: {
    display: 'inline-block',
    width: '0.6em',
    height: '1em',
    background: 'var(--ink-white)',
    verticalAlign: '-0.13em',
    animation: 'cm-blink 1s var(--ease-step-coarse) infinite'
  },
  scan: {
    position: 'absolute',
    inset: 0,
    background: 'var(--texture-scanlines)',
    pointerEvents: 'none'
  }
};
function Terminal({
  lines = [],
  title,
  prompt = '>',
  caret = true,
  chrome = true,
  height,
  scanlines = true,
  style,
  ...rest
}) {
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      ...terminalStyles.root,
      ...style
    }
  }), chrome && /*#__PURE__*/React.createElement("div", {
    style: terminalStyles.chrome
  }, /*#__PURE__*/React.createElement("span", {
    style: terminalStyles.pip
  }), /*#__PURE__*/React.createElement("span", {
    style: terminalStyles.pip
  }), /*#__PURE__*/React.createElement("span", {
    style: terminalStyles.pip
  }), title && /*#__PURE__*/React.createElement("span", {
    style: terminalStyles.title
  }, title)), /*#__PURE__*/React.createElement("div", {
    style: {
      ...terminalStyles.body,
      height,
      maxHeight: height
    }
  }, lines.map((l, i) => {
    const line = typeof l === 'string' ? {
      text: l
    } : l;
    return /*#__PURE__*/React.createElement("div", {
      key: i,
      style: {
        ...terminalStyles.line,
        color: terminalTones[line.tone] || terminalTones.out
      }
    }, /*#__PURE__*/React.createElement("span", {
      style: {
        flex: 'none',
        color: 'var(--text-disabled)'
      }
    }, line.prompt ?? prompt), /*#__PURE__*/React.createElement("span", null, line.text));
  }), caret && /*#__PURE__*/React.createElement("div", {
    style: {
      ...terminalStyles.line,
      color: 'var(--text-primary)'
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      flex: 'none',
      color: 'var(--text-disabled)'
    }
  }, prompt), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: terminalStyles.caret
  }))), scanlines && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: terminalStyles.scan
  }));
}

export { Terminal };
