// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
/** The eight archetypes from the brand book's CHARACTER FAMILY plate. */
const CHARACTERS = ['oracle', 'monk', 'watcher', 'keeper', 'archivist', 'pilgrim', 'ghost', 'machine-priest'];
const characterPortraitStyles = {
  root: {
    display: 'inline-flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 'var(--space-5)',
    minWidth: 0
  },
  name: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-2xs)',
    fontWeight: 'var(--weight-medium)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    whiteSpace: 'nowrap'
  }
};
function CharacterPortrait({
  name = 'oracle',
  size = 160,
  tint,
  label,
  basePath = 'assets/characters',
  style,
  ...rest
}) {
  const url = `${basePath}/${name}.png`;
  const figure = tint ? /*#__PURE__*/React.createElement("span", {
    role: "img",
    "aria-label": name,
    style: {
      display: 'block',
      flex: 'none',
      height: size,
      width: Math.round(size * (96 / 163)),
      background: tint,
      WebkitMaskImage: `url("${url}")`,
      maskImage: `url("${url}")`,
      WebkitMaskSize: 'contain',
      maskSize: 'contain',
      WebkitMaskRepeat: 'no-repeat',
      maskRepeat: 'no-repeat',
      WebkitMaskPosition: 'center',
      maskPosition: 'center'
    }
  }) : /*#__PURE__*/React.createElement("img", {
    src: url,
    alt: name,
    style: {
      display: 'block',
      flex: 'none',
      height: size,
      width: 'auto',
      imageRendering: 'pixelated'
    }
  });
  return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    style: {
      ...characterPortraitStyles.root,
      ...style
    }
  }), figure, label !== false && /*#__PURE__*/React.createElement("span", {
    style: characterPortraitStyles.name
  }, label || name.replace('-', ' ')));
}

export { CHARACTERS, CharacterPortrait };
