// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const textureFieldStyles = {
  root: {
    position: 'relative',
    minWidth: 0
  },
  layer: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none'
  },
  content: {
    position: 'relative'
  }
};

/**
 * Stacks the brand book's PATTERN & TEXTURE plates behind arbitrary content.
 * grid + vignette is the default page treatment for CabalMesh screens.
 */
function TextureField({
  grid = true,
  gridScale = 'fine',
  scanlines = false,
  vignette = true,
  dither = false,
  glitch = false,
  opacity = 1,
  basePath = 'assets/textures',
  children,
  style,
  ...rest
}) {
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      ...textureFieldStyles.root,
      background: 'var(--surface-page)',
      ...style
    }
  }), grid && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...textureFieldStyles.layer,
      backgroundImage: 'var(--texture-grid)',
      backgroundSize: gridScale === 'coarse' ? 'var(--texture-grid-coarse-size)' : 'var(--texture-grid-size)',
      opacity
    }
  }), dither && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...textureFieldStyles.layer,
      backgroundImage: `url("${basePath}/dither.png")`,
      backgroundSize: '256px 256px',
      imageRendering: 'pixelated',
      opacity: 0.18,
      mixBlendMode: 'screen'
    }
  }), glitch && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...textureFieldStyles.layer,
      backgroundImage: `url("${basePath}/glitch.png")`,
      backgroundSize: '272px 376px',
      imageRendering: 'pixelated',
      opacity: 0.2,
      mixBlendMode: 'screen'
    }
  }), scanlines && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...textureFieldStyles.layer,
      background: 'var(--texture-scanlines)'
    }
  }), vignette && /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...textureFieldStyles.layer,
      background: 'var(--texture-vignette)'
    }
  }), /*#__PURE__*/React.createElement("div", {
    style: textureFieldStyles.content
  }, children));
}

export { TextureField };
