// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetOption = { name: string, 
/**
 * Three-letter tag the board shows beside the name.
 */
tag: string, decimals: number, };

/**
 * Delta direction. Domain matches `StatBlock`'s `deltaTone`.
 */
export type DeltaTone = "up" | "down" | "neutral";

/**
 * Why an intent failed. A variant rather than a message, so the UI can render
 * on-voice copy instead of echoing an internal string.
 */
export type FailureReason = "no_route" | "node_failure" | "condition_unmet" | "settlement_rejected" | "insufficient_balance";

/**
 * The options the compose screen offers.
 */
export type FormOptions = { actions: Array<string>, assets: Array<AssetOption>, conditions: Array<string>, modes: Array<ModeOption>, privacyLevels: Array<string>, };

/**
 * An intent as the detail screen renders it: the list row plus the full
 * request, so opening a detail never needs a second round trip for the parts
 * the list already fetched.
 *
 * The draft is rendered as formatted strings rather than the raw domain type:
 * a `TokenAmount`'s `u128` does not survive a JS number, and the boundary rule
 * is that numbers are formatted once, in Rust.
 */
export type IntentDetail = { 
/**
 * The list-row view, nested so its `amount` does not collide with the
 * detail's own formatted fields.
 */
view: IntentView, 
/**
 * The composed action, e.g. `BUY`.
 */
action: string, 
/**
 * The asset, e.g. `SOL`.
 */
asset: string, 
/**
 * The condition as a sentence, e.g. `UNDER $95.00`.
 */
condition: string, 
/**
 * The amount with its asset, e.g. `10 SOL`.
 */
amount: string, 
/**
 * The execution mode label, e.g. `SHARK MODE`.
 */
mode: string, 
/**
 * The privacy level, e.g. `MEDIUM`.
 */
privacy: string, };

/**
 * Which slice of the list to return.
 */
export type IntentFilter = "ACTIVE" | "PENDING" | "HISTORY";

/**
 * Where an intent is in its life.
 *
 * Matched exhaustively everywhere — no catch-all arm — so adding a variant
 * surfaces every place that has to decide what it means, rather than silently
 * falling through to a default.
 */
export type IntentStatus = { "status": "DRAFT" } | { "status": "BROADCAST", route_len: number, } | { "status": "NEGOTIATING", bids: number, best: UsdPrice | null, } | { "status": "FINDING_ROUTE" } | { "status": "WAITING" } | { "status": "SETTLED", proof: ProofHash, filled_at: UsdPrice, elapsed_ms: number, } | { "status": "FAILED", reason: FailureReason, } | { "status": "CANCELLED" };

/**
 * An intent as a list row renders it.
 */
export type IntentView = { id: string, 
/**
 * e.g. `BUY SOL`.
 */
title: string, 
/**
 * e.g. `UNDER $95`.
 */
subtitle: string, 
/**
 * Execution mode, shown as a badge. Absent when default.
 */
badge: string | null, amount: string, 
/**
 * The lifecycle state, driving both the status text and the dot tone.
 */
status: IntentStatus, 
/**
 * Elapsed or settled time, e.g. `2M 14S` or `11.4S`.
 */
elapsed: string, };

/**
 * One rendered terminal line.
 *
 * `Box<str>` rather than `String`: these are built once, never mutated, and
 * arrive in the hundreds, so `String`'s spare-capacity word is dead weight.
 */
export type LogLine = { text: string, tone: LogTone, };

/**
 * Terminal line tone. Domain matches `TerminalLine`.
 */
export type LogTone = "out" | "dim" | "ok" | "err" | "info" | "loud";

/**
 * What the home screen renders.
 */
export type MeshSnapshotView = { 
/**
 * Truncated for display, e.g. `7F3A..8C2E`.
 */
nodeId: string, 
/**
 * Uptime in the board's format, e.g. `3D 14H 22M`.
 */
uptime: string, connected: boolean, stats: Array<StatTile>, };

/**
 * What `export_mnemonic` returns: the AI's narrative anchoring the seed
 * words in order. The mnemonic itself never crosses to the webview here —
 * the story is the recall aid, and the words are shown only by
 * `copy_mnemonic`/a dedicated reveal step the user explicitly opens.
 */
export type MnemonicExport = { 
/**
 * The AI-written story. A memory aid, never part of the secret.
 */
story: string, };

export type ModeOption = { label: string, description: string, };

/**
 * A peer, as the nodes screen shows it.
 *
 * **No distance.** A libp2p peer has an identifier and an address, not
 * coordinates, and this app requests no location permission — asking for one
 * would contradict the entire premise. The prototype's `1.2 km` is canned;
 * rendering it would be a fabricated measurement.
 */
export type NodeSummary = { 
/**
 * Truncated peer id, e.g. `8A3F..1209`.
 */
id: string, 
/**
 * Round-trip time where known.
 */
latencyMs: number | null, 
/**
 * 1 is direct; more means relayed.
 */
hops: number, transport: Transport, 
/**
 * Deterministic map position in [0,1], seeded by peer id.
 */
x: number, y: number, 
/**
 * Milliseconds, also seeded, so the field does not pulse in unison.
 */
pulseMs: number, };

/**
 * What the profile screen shows.
 */
export type ProfileView = { nodeId: string, 
/**
 * `87.6 (+5.3%)`, or an em dash with no mesh. Derived from real
 * demonstrated behaviour — see src/reputation.rs.
 */
reputation: string, memberSince: string, offline: boolean, network: string, 
/**
 * Whether transactions here move real value.
 */
isTestnet: boolean, };

export type ActivityEntry = { id: string, kind: string, summary: string, createdAt: number, };
export type ActivityLogView = { entries: Array<ActivityEntry>, broadcastCount: number, settledCount: number, cancelledCount: number, relayedCount: number, };
export type AchievementView = { id: string, title: string, description: string, progress: number, target: number, status: string, nftAddress: string | null, };

/**
 * A settlement proof hash. Displayed lowercase and unabbreviated.
 */
export type ProofHash = string;

/**
 * One row of the confirm dialog.
 */
export type ReviewRow = { key: string, value: string, };

/**
 * What the splash screen needs to decide what it is offering.
 */
export type SessionStatus = { 
/**
 * Whether bootstrap has finished and the mesh is usable.
 */
ready: boolean, 
/**
 * Truncated node id, e.g. `7F3A..8C2E`. Absent before bootstrap.
 */
nodeId: string | null, 
/**
 * Whether a peer is reachable right now.
 */
connected: boolean, };

/**
 * A home-screen stat tile, pre-formatted.
 *
 * The frontend renders these verbatim. Sending a raw number and formatting it
 * there would mean reimplementing the separator and precision rules per
 * screen, and drifting from them.
 */
export type StatTile = { label: string, 
/**
 * Already separated, e.g. `1,248`.
 */
value: string, 
/**
 * Already signed and suffixed, e.g. `+12.4%`. Absent when unmeasured.
 */
delta: string | null, deltaTone: DeltaTone, };

/**
 * Status tone. Domain matches the design system's `StatusDot` prop exactly.
 */
export type StatusTone = "online" | "alert" | "info" | "idle" | "offline";

/**
 * Toast tone. Domain matches `Toast`.
 */
export type ToastTone = "neutral" | "info" | "success" | "alert";

/**
 * How a peer is reached.
 */
export type Transport = "mdns" | "quic" | "relayed";

/**
 * A USD price, fixed at two decimal places — the precision the UI shows
 * (`$94.21`, `UNDER $95`).
 */
export type UsdPrice = { 
/**
 * Cents. Avoids the float rounding that makes price comparisons lie.
 */
cents: bigint, };

/**
 * A row in the vault list.
 */
export type VaultRow = { 
/**
 * Three-letter tag, e.g. `AVX`, `ID`, `KEY`.
 */
tag: string, name: string, amount: string, 
/**
 * Secondary line. Absent when there is nothing true to say.
 */
detail: string | null, };
