// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const dialogStyles = {
  scrim: {
    position: 'fixed',
    inset: 0,
    background: 'var(--surface-scrim)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 'var(--space-9)',
    zIndex: 'var(--z-modal)',
    backdropFilter: 'blur(2px)'
  },
  shell: {
    position: 'relative',
    width: '100%',
    background: 'var(--surface-panel)',
    border: 'var(--border-width) solid var(--border-strong)',
    boxShadow: 'var(--glow-white)'
  },
  head: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-5)',
    padding: 'var(--space-6) var(--space-8)',
    borderBottom: 'var(--border-width) solid var(--border-hairline)'
  },
  title: {
    fontFamily: 'var(--font-display)',
    fontSize: 'var(--text-base)',
    letterSpacing: 'var(--tracking-wider)',
    textTransform: 'uppercase',
    color: 'var(--text-primary)'
  },
  close: {
    marginLeft: 'auto',
    background: 'none',
    border: 0,
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-base)',
    lineHeight: 1,
    padding: 'var(--space-2)'
  },
  body: {
    padding: 'var(--space-8)',
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-base)',
    lineHeight: 'var(--leading-normal)'
  },
  foot: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 'var(--space-5)',
    padding: 'var(--space-6) var(--space-8)',
    borderTop: 'var(--border-width) solid var(--border-hairline)'
  },
  ticks: [{
    top: 3,
    left: 3,
    borderTopWidth: 1,
    borderLeftWidth: 1
  }, {
    top: 3,
    right: 3,
    borderTopWidth: 1,
    borderRightWidth: 1
  }, {
    bottom: 3,
    left: 3,
    borderBottomWidth: 1,
    borderLeftWidth: 1
  }, {
    bottom: 3,
    right: 3,
    borderBottomWidth: 1,
    borderRightWidth: 1
  }]
};
function Dialog({
  open = true,
  title,
  onClose,
  footer,
  width = 480,
  children,
  style,
  ...rest
}) {
  if (!open) return null;
  return /*#__PURE__*/React.createElement("div", {
    style: dialogStyles.scrim,
    role: "presentation",
    onClick: onClose
  }, /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    role: "dialog",
    "aria-modal": "true",
    "aria-label": typeof title === 'string' ? title : undefined,
    onClick: e => e.stopPropagation(),
    style: {
      ...dialogStyles.shell,
      maxWidth: width,
      ...style
    }
  }), dialogStyles.ticks.map((c, i) => /*#__PURE__*/React.createElement("span", {
    key: i,
    "aria-hidden": "true",
    style: {
      position: 'absolute',
      width: 6,
      height: 6,
      borderStyle: 'solid',
      borderWidth: 0,
      borderColor: 'var(--border-loud)',
      ...c
    }
  })), (title || onClose) && /*#__PURE__*/React.createElement("div", {
    style: dialogStyles.head
  }, title && /*#__PURE__*/React.createElement("span", {
    style: dialogStyles.title
  }, title), onClose && /*#__PURE__*/React.createElement("button", {
    type: "button",
    "aria-label": "Close",
    onClick: onClose,
    style: dialogStyles.close
  }, "\xD7")), /*#__PURE__*/React.createElement("div", {
    style: dialogStyles.body
  }, children), footer && /*#__PURE__*/React.createElement("div", {
    style: dialogStyles.foot
  }, footer)));
}

export { Dialog };
