// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const toastTones = {
  neutral: {
    accent: 'var(--border-strong)',
    color: 'var(--text-secondary)'
  },
  info: {
    accent: 'var(--accent-neon-blue)',
    color: 'var(--text-secondary)'
  },
  success: {
    accent: 'var(--accent-acid-green)',
    color: 'var(--text-secondary)'
  },
  alert: {
    accent: 'var(--accent-blood-red)',
    color: 'var(--text-secondary)'
  }
};
const toastStyles = {
  root: {
    position: 'relative',
    display: 'flex',
    alignItems: 'flex-start',
    gap: 'var(--space-5)',
    minWidth: 280,
    maxWidth: 400,
    padding: 'var(--space-5) var(--space-6)',
    background: 'var(--surface-raised)',
    border: 'var(--border-width) solid var(--border-default)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-sm)'
  },
  bar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 2
  },
  title: {
    display: 'block',
    fontSize: 'var(--text-2xs)',
    letterSpacing: 'var(--tracking-widest)',
    textTransform: 'uppercase',
    color: 'var(--text-muted)',
    marginBottom: 'var(--space-2)'
  },
  close: {
    marginLeft: 'auto',
    background: 'none',
    border: 0,
    color: 'var(--text-disabled)',
    cursor: 'pointer',
    fontSize: 'var(--text-base)',
    lineHeight: 1,
    padding: 0
  },
  stack: {
    position: 'fixed',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-4)',
    zIndex: 'var(--z-toast)'
  }
};
function Toast({
  tone = 'neutral',
  title,
  icon,
  onClose,
  children,
  style,
  ...rest
}) {
  const t = toastTones[tone] || toastTones.neutral;
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    role: "status",
    style: {
      ...toastStyles.root,
      ...style
    }
  }), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      ...toastStyles.bar,
      background: t.accent
    }
  }), icon && /*#__PURE__*/React.createElement("span", {
    style: {
      flex: 'none',
      color: t.accent,
      display: 'inline-flex',
      marginTop: 2
    }
  }, icon), /*#__PURE__*/React.createElement("span", {
    style: {
      minWidth: 0,
      color: t.color
    }
  }, title && /*#__PURE__*/React.createElement("span", {
    style: toastStyles.title
  }, title), children), onClose && /*#__PURE__*/React.createElement("button", {
    type: "button",
    "aria-label": "Dismiss",
    onClick: onClose,
    style: toastStyles.close
  }, "\xD7"));
}
function ToastStack({
  placement = 'bottom-right',
  gap = 'var(--space-8)',
  children,
  style,
  ...rest
}) {
  const pos = {
    'top-right': {
      top: gap,
      right: gap
    },
    'top-left': {
      top: gap,
      left: gap
    },
    'bottom-right': {
      bottom: gap,
      right: gap
    },
    'bottom-left': {
      bottom: gap,
      left: gap
    }
  }[placement];
  return /*#__PURE__*/React.createElement("div", _extends({}, rest, {
    style: {
      ...toastStyles.stack,
      ...pos,
      ...style
    }
  }), children);
}

export { Toast, ToastStack };
