// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
const tooltipStyles = {
  wrap: {
    position: 'relative',
    display: 'inline-flex'
  },
  bubble: {
    position: 'absolute',
    zIndex: 'var(--z-tooltip)',
    padding: 'var(--space-3) var(--space-5)',
    background: 'var(--ink-white)',
    color: 'var(--text-inverse)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-2xs)',
    fontWeight: 'var(--weight-medium)',
    letterSpacing: 'var(--tracking-wider)',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    pointerEvents: 'none',
    borderRadius: 'var(--radius-none)'
  }
};
const tooltipPlacements = {
  top: {
    bottom: 'calc(100% + 6px)',
    left: '50%',
    transform: 'translateX(-50%)'
  },
  bottom: {
    top: 'calc(100% + 6px)',
    left: '50%',
    transform: 'translateX(-50%)'
  },
  left: {
    right: 'calc(100% + 6px)',
    top: '50%',
    transform: 'translateY(-50%)'
  },
  right: {
    left: 'calc(100% + 6px)',
    top: '50%',
    transform: 'translateY(-50%)'
  }
};
function Tooltip({
  label,
  placement = 'top',
  children,
  style,
  ...rest
}) {
  const [open, setOpen] = React.useState(false);
  return /*#__PURE__*/React.createElement("span", _extends({}, rest, {
    style: {
      ...tooltipStyles.wrap,
      ...style
    },
    onMouseEnter: () => setOpen(true),
    onMouseLeave: () => setOpen(false),
    onFocus: () => setOpen(true),
    onBlur: () => setOpen(false)
  }), children, open && /*#__PURE__*/React.createElement("span", {
    role: "tooltip",
    style: {
      ...tooltipStyles.bubble,
      ...tooltipPlacements[placement]
    }
  }, label));
}

export { Tooltip };
