#!/usr/bin/env python3
"""Split the design-system bundle back into source files.

WHY

The design system is delivered as `_ds_bundle.js`: a precompiled IIFE that
attaches every component to `window.CabalMeshDS` and assumes a global `React`.
Shipping that means no tree-shaking (all 30 components in every screen), no
types, no readable source, a global React shim, and — worst — a file marked
"Generated, never edit" that has to be edited immediately for the touch and
hover fixes.

It is unminified and cleanly delimited per source file, so splitting it back is
mechanical. This script is that split, kept in the repo so replacing the
vendored tree is a command rather than an archaeology exercise.

USAGE

    python3 scripts/unbundle-ds.py "/path/to/_ds_bundle.js"

Overwrites src/ds/components/. Regenerate types afterwards with
scripts/generate-ds-types.py.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPONENTS = ROOT / "src" / "ds" / "components"

HEADER = """// Vendored from the CabalMesh design system bundle.
//
// GENERATED by scripts/unbundle-ds.py — do not edit.
//
// Local adaptations belong in ds/mobile.css. This tree is replaced wholesale
// when the design system is regenerated, so anything changed here is lost.
import React from 'react';

"""

# Each component in the bundle is wrapped as:
#   try { (() => { ...source... })(); } catch (e) { ...path: "components/X.jsx"
SECTION = re.compile(
    r'try \{ \(\(\) => \{\n(.*?)\n\}\)\(\); \} catch \(e\) \{ '
    r'__ds_ns\.__errors\.push\(\{ path: "([^"]+)"',
    re.S,
)

# The bundle's own registration into its global scope object. ES exports
# replace it, and leaving it in throws a ReferenceError at module load —
# which takes down the entire bundle, not just the component.
REGISTRATION = re.compile(r'^Object\.assign\(__ds_scope, \{[^}]*\}\);\s*$', re.M)

DECLARATION = re.compile(r'^(?:function|const|class)\s+([A-Z][A-Za-z0-9_]*)', re.M)


def main() -> int:
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    bundle = Path(sys.argv[1])
    if not bundle.is_file():
        sys.exit(f"bundle not found: {bundle}")

    source = bundle.read_text(encoding="utf-8")
    manifest: dict[str, list[str]] = {}

    for match in SECTION.finditer(source):
        body, path = match.group(1), match.group(2)
        if not path.startswith("components/"):
            continue  # ui_kits and canned data are prototype-only

        body = REGISTRATION.sub("", body).rstrip()
        if "__ds_scope" in body or "__ds_ns" in body:
            sys.exit(f"{path}: unhandled bundle scaffolding remains — inspect before shipping")

        names = sorted(set(DECLARATION.findall(body)))
        destination = COMPONENTS.parent / path
        destination.parent.mkdir(parents=True, exist_ok=True)

        exports = f"\n\nexport {{ {', '.join(names)} }};\n" if names else "\n"
        destination.write_text(HEADER + body + exports, encoding="utf-8")
        manifest[path] = names

    write_barrel(manifest)

    total = sum(len(names) for names in manifest.values())
    print(f"wrote {len(manifest)} files, {total} exports")
    return 0


def write_barrel(manifest: dict[str, list[str]]) -> None:
    """The single public entry the adherence lint requires screens to use."""
    lines = [
        "// The design system's public exports.",
        "//",
        "// GENERATED by scripts/unbundle-ds.py — do not edit.",
        "//",
        "// The adherence lint forbids importing component internals, so screens",
        "// import from here. That is what lets the vendored tree be replaced",
        "// wholesale without touching a single screen.",
        "",
    ]
    for path in sorted(manifest):
        names = manifest[path]
        if not names:
            continue
        module = "./" + path[len("components/"):].removesuffix(".jsx")
        lines.append(f"export {{ {', '.join(names)} }} from '{module}';")

    (COMPONENTS / "index.js").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
